server:
  port: 8080
  
spring:
  application:
    name: Server-Provider
eureka:
  instance:
    hostname: peer1
    appname: Server-Provider
    app-group-name: Register
  client:
    serviceUrl:
      defaultZone: http://peer2:8081/eureka/
  server:
    # 当大量服务挂了，认为是网络问题而不是服务本身挂了，所以配置false
    enable-self-preservation: false