server:
  port: 8081
  
spring:
  application:
    name: Server-Provider
    
eureka:
  instance:
    # 必须修改本地的host文件，否则无法部署
    hostname: peer2
    appname: Server-Provider
    app-group-name: Register
  client:
    serviceUrl:
      defaultZone: http://peer1:8080/eureka/
  server:
    enable-self-preservation: false